name: Bug Report
description: Create a report to help us improve.
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide a clear and concise description of the bug.
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      placeholder: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: A clear description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: If applicable, add screenshots to help explain your problem.
